apiVersion: v1
kind: Service
metadata:
  name: nginx-frontend
  namespace: skripsi-hpa
spec:
  type: NodePort
  selector:
    app: nginx-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
